print('')
print("Hello wordl!";)
print("Hello everbody";)
print("Hello";)
print("Hello my dear friend";)
print("Glad to see you")
print("Hello wordl!")
print("Hello everbody")
print("Hello")
print("Hello my dear friend")
print("Glad to seeeeee you")
